spring:
  datasource:
    username: root
    password: hackme
    url: jdbc:mysql://localhost:3306/cadastros
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

limite:
  cadastros: 5